enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
cli-source = "MorpheApp/morphe-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/znarfm/revanced-apks/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Morphe
[YouTube-Morphe]
app-name = "YouTube"
rv-brand = "Morphe"
arch = "arm64-v8a"
patches-source = "MorpheApp/morphe-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
# Do not change icon and app name
excluded-patches = "'Custom branding'"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"

[YTMusic-Morphe]
app-name = "YT Music"
rv-brand = "Morphe"
arch = "arm64-v8a"
patches-source = "MorpheApp/morphe-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
# Do not change icon and app name
excluded-patches = "'Custom branding'"

[Reddit-Morphe]
app-name = "Reddit"
apkmirror-dpi = "nodpi anydpi 120-640dpi"
arch = "arm64-v8a"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

# De-Revanced (Revanced patches ported to Morphe)
[GooglePhotos]
app-name = "GPhotos"
arch = "arm64-v8a"
patches-source = "RookieEnough/De-ReVanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Strava]
arch = "arm64-v8a"
patches-source = "RookieEnough/De-ReVanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/"
uptodown-dlurl = "https://strava.en.uptodown.com/android/download"
